[bumpver]
current_version = "2021.34.0"
version_pattern = "GGGG.VV.PATCH"
commit_message = "Bump to {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{version}"',
]
