name: Bump Patch Version

on:
  workflow_dispatch:

jobs:
  update:
    name: Bump patch version
    runs-on: ubuntu-latest
    steps:

    - name: Checkout addon code
      uses: actions/checkout@v2
      # need to use the personal access token (PAT) so that this workflow can trigger other
      # workflows. See https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install bumpver
      run: |
        pip install bumpver

    - name: Configure git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Bump minor version
      run: |
        bumpver update --patch

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_PAT }}
        branch: ${{ github.ref }}
        tags: true
