name: Bump Patch Version

on:
  workflow_dispatch:

jobs:
  update:
    name: Bump patch version
    runs-on: ubuntu-latest
    steps:

    - name: Checkout addon code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install bumpver
      run: |
        pip install bumpver

    - name: Configure git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Bump minor version
      run: |
        bumpver update --patch

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true
