name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install and run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: --no-color

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: check
    # Run only on pushing a tag
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install wap
      run: |
        pip install wow-addon-packager==0.7.1

    - name: Get version from tag
      id: version-tag
      run: |
        echo "::set-output name=version::$(git describe --always --tags --exact-match)"
      shell: bash

    - name: Build
      run: |
        wap build --addon-version "$ITEMVERSION_RELEASE_VERSION"
      env:
        ITEMVERSION_RELEASE_VERSION: ${{ steps.version-tag.outputs.version }}

    - name: Upload
      run: |
        wap upload --addon-version "$ITEMVERSION_RELEASE_VERSION" --release-type release
      env:
        WAP_CURSEFORGE_TOKEN: ${{ secrets.CF_API_KEY }}
        ITEMVERSION_RELEASE_VERSION: ${{ steps.version-tag.outputs.version }}

    - name: Upload GitHub release assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
