name: Refresh Data

env:
  PIP_CACHE: ~/.pip_cache
  POETRY_CACHE: ~/.poetry_cache
  ITEM_VERSION_SCRAPE_DATA_CACHE: ~/.cache/itemversionscrape

on:
  workflow_dispatch:
  schedule:
  # run on tuesdays at 16:00 UTC (1 hour after wow weekly reset)
  # also, by default, this runs on the last commit on the default branch (master)
  - cron:  '0 16 * * 2'

jobs:
  refresh:
    name: Refresh item data
    runs-on: ubuntu-latest
    steps:

    - name: Checkout scrape code
      uses: actions/checkout@v2
      with:
        repository: t-mart/ItemVersion-Scrape
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Retrieve dependency cache
      id: dep-cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.POETRY_CACHE }}
          ${{ env.PIP_CACHE }}
        key: deps-${{ hashFiles('poetry.lock') }}

    - name: Get Date (for data cache hash)
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%GW%V")"
      shell: bash

    - name: Retrieve data cache
      uses: actions/cache@v2
      with:
        path: ${{ env.ITEM_VERSION_SCRAPE_DATA_CACHE }}
        key: scrape-data-debug1-${{ steps.get-date.outputs.date }}

    - name: Install system dependencies
      run: |
        python -m pip install --cache-dir ${{ env.PIP_CACHE }} --upgrade pip poetry

    - name: Install project dependencies
      run: |
        poetry config cache-dir ${{ env.POETRY_CACHE }}
        poetry install -vvv

    - name: Refresh Data.lua
      run: |
        poetry run scrape > Data.lua

    - name: Upload generated lua artifact
      uses: actions/upload-artifact@v2
      with:
        name: Data.lua
        path: Data.lua

  update:
    name: Update repository
    runs-on: ubuntu-latest
    needs: refresh
    steps:

    - name: Checkout addon code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install bumpver
      run: |
        pip install bumpver

    - name: Download generated lua artifact
      uses: actions/download-artifact@v2
      with:
        name: Data.lua

    - name: Commit Data.lua changes
      run: |
        mv Data.lua ItemVersion
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ItemVersion/Data.lua
        git status
        git commit -m "Refresh item data"

    - name: Bump version
      run: |
        bumpver update --dry && bumpver update || bumpver update --patch

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_PAT }}
        branch: ${{ github.ref }}
        tags: true
